### ISSUE TITLE
Remaining work to be done before Friday's deliverable

### ISSUE THREAD

**Issue by FulelaMjali** [LesegoGomolemo/MiniProject-Phase3-G9#1]
@khodanit Please download and go through the reader function code and generate an Authentication log file that we could use to test the reader. Also feel free to add the functionality to the reader Class. @JustinG123 will upload the Main file which will run and produce the report.

**Comment by khodanit** [comment]
I'm not sure I understand the code but I think it is failing to run with my log file. Can you try it on your side. I've also added a template log file generator that we can use to quickly create a string of text. I'd like to edit it so that it actually generates a file.

**Comment by FulelaMjali** [comment]
If you're running the program on Netbeans it requires you to enter the entire path of where the file to be opened is located i.e C:\Users\...etc .

**Comment by khodanit** [comment]
Will look into it. Were we suppose to meet today? Since I missed the meeting yesterday

**Comment by khodanit** [comment]
It works. Thanks for the tip. If we need to add more logs we can easily generate them tomorrow using the template... I'm not sure how Justin is planning on creating the output for the report. I think if we can get direction on that then we can just add more functionality based on it.
